#ifndef COMMON_H_
#define COMMON_H_

#define FONT_OPENSANS_EXTRA_48_NUMBERS RESOURCE_ID_FONT_OPENSANS_EXTRA_52_NUMBERS
#define FONT_OPENSANS_LIGHT_24_TEXT RESOURCE_ID_FONT_OPENSANS_LIGHT_24_TEXT
#define FONT_OPENSANS_BOLD_24_NUMBERS RESOURCE_ID_FONT_OPENSANS_BOLD_24_NUMBERS
#define FONT_OPENSANS_EXTRA_24_TEXT RESOURCE_ID_FONT_OPENSANS_EXTRA_24_TEXT

#define NMEA_REMOTE_SPLASH RESOURCE_ID_NMEA_REMOTE_SPLASH

#define SMILE_DEFAULT_VALUE "--.-"
#define ANGLE_DEFAULT_VALUE "---°"

#define APP_TIMER_TIMEOUT 1000

#define MIN(x, y) (x < y ? x : y)
#define MAX(x, y) (x > y ? x : y)

enum NMEAkey {
	SPEED_KEY = 0,  
	HDG_KEY = 1,
	AWA_KEY = 2,	  	
	BTW_KEY = 3,	  	
	DTW_KEY = 4,	  	
	TTG_KEY = 5
};

#endif /* COMMON_H_ */
